name: Build
on:
  push:
    branches: [ "main", "develop" ]

jobs:
  prepare:
    name: Prepare
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ivaoaero'
  build:
    name: Build
    runs-on: self-hosted
    needs:
      - prepare
    steps:
      - uses: actions/cache@v3
        with:
          path: common/temp/pnpm-store
          key: common/config/rush/pnpm-lock.yaml
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Rush build
        run: node common/scripts/install-run-rush.js rebuild --verbose
