name: Build and deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
      - name: 'Install dependencies'
        shell: bash
        run: |
          npm ci
      - name: 'Build eslint-config package'
        shell: bash
        run: |
          npm run build -w packages/eslint-config
      - name: 'Build brand package'
        shell: bash
        run: |
          npm run build -w packages/brand
      - name: 'Build react-components'
        shell: bash
        run: |
          npm run build -w packages/react-components
          npm run build-storybook -w packages/react-components
      - name: 'Upload artifact'
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: packages/react-components/storybook-static
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: self-hosted
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: build-publish
        uses: actions/deploy-pages@v1
      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: github-pages