name: Build and deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: 'Build storybook'
        shell: bash
        run: |
          cd packages/react-components
          npm ci
          npm run build-storybook
      - name: 'Upload artifact'
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: packages/react-components/storybook-static
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: self-hosted
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: build-publish
        uses: actions/deploy-pages@v1
      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: github-pages