name: _reusable build workflow

on:
  workflow_call:

jobs:
  build:
    name: Build TypeScript files
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ivaoaero'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts --strict-peer-dependencies

      - name: Build atmosphere packages
        run: pnpm -r build

      - name: Upload brand artifacts
        uses: actions/upload-artifact@v4
        with:
          name: brand-build
          path: brand/dist

      - name: Upload react-components artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-components-build
          path: components/react/dist
