name: Pull Request
on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - review_requested

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ivaoaero'
      - uses: actions/cache@v3
        with:
          path: common/temp/pnpm-store
          key: common/config/rush/pnpm-lock.yaml
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Build
        run: node common/scripts/install-run-rush.js build
