name: Release package

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  id-token: write # for npm OIDC
  contents: read # for checkout

env:
  CI: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  release:
    needs:
      - build
    if: success('build')
    name: Release atmosphere packages
    runs-on: ubuntu-24.04
    environment: default # environment with NPM_TOKEN
    permissions:
      contents: write # publish a GitHub release
      id-token: write # use OIDC for npm provenance
      issues: write # comment on released issues
      packages: write # publish a NPM package
      pull-requests: write # comment on released pull requests
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org # https://github.com/changesets/changesets/issues/1152#issuecomment-3593077008
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts --strict-peer-dependencies

      - name: Debug NPM
        run: npm -v

      - name: Downloading brand artifacts
        uses: actions/download-artifact@v7
        with:
          name: brand-build
          path: brand/dist

      - name: Downloading react-components artifacts
        uses: actions/download-artifact@v7
        with:
          name: react-components-build
          path: components/react/dist

      - name: Release atmosphere packages
        uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: ${{ github.ref == 'refs/heads/main' && 'pnpm ci:release' || 'pnpm ci:prerelease'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
